name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.13.0
  flutter_cache_manager: ^3.1.2
  files_gallery:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
