name: files_gallery
description: Display galleries in flutter.
version: 0.0.1
author:
homepage: https://github.com/resvu/flutter-files-gallery

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  transparent_image: ^1.0.0
  flutter_svg: ^0.17.4
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.6.5
  crypto: ^2.1.3
  flutter_native_image: ^0.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fileicons/
