name: files_gallery
description: A new Flutter package project.
version: 0.0.1
author:
homepage: https://github.com/resvu/flutter-files-gallery

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  transparent_image: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
